// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson94d9f80aDecodeRestServiceModel(in *jlexer.Lexer, out *ResponseModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "html":
			if in.IsNull() {
				in.Skip()
				out.HTML = nil
			} else {
				out.HTML = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94d9f80aEncodeRestServiceModel(out *jwriter.Writer, in ResponseModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"html\":"
		out.RawString(prefix[1:])
		out.Base64Bytes(in.HTML)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94d9f80aEncodeRestServiceModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94d9f80aEncodeRestServiceModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94d9f80aDecodeRestServiceModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94d9f80aDecodeRestServiceModel(l, v)
}
